### ISSUE TITLE
close error

### ISSUE THREAD

**Issue by inkroom** [electerm/electerm#1095]
## Expected Behavior

exit
## Steps to Reproduce

1.exit program
2. a dialog say " Error: kill ESRCH  "

## Error
![_ _20190122183342](https://user-images.githubusercontent.com/27911304/51529722-41c54e00-1e74-11e9-831f-2ab5489450d5.png)

**Comment by zxdong262** [comment]
Hi @inkroom,

So this happens every time you close electerm?

**Comment by zxdong262** [comment]
Can you run electerm from command line, and post the log here?

**Comment by inkroom** [comment]
@zxdong262 when I open multiple remote ssh，and I close a tab , the other ssh also lose connect. then close the program ,,error

the log is here

``` base
error parsing $HOME/.ssh/config
maybe no $HOME/.ssh/config, but it is ok
no ../../install-src file
[09:05:04.359] [info] App starting...
no /home/inkbox/.config/electerm-config.js but it is ok
no ../../install-src file
Wed Jan 23 2019 09:05:04 GMT+0800 (CST) server runs on localhost 3075
shortcut Registration failed.
Wed Jan 23 2019 09:05:05 GMT+0800 (CST) Created terminal with PID: s4b60hNpS
Wed Jan 23 2019 09:05:05 GMT+0800 (CST) Connected to terminal s4b60hNpS
Wed Jan 23 2019 09:05:05 GMT+0800 (CST) Resized terminal  s4b60hNpS  to  91  cols and  20  rows.
Wed Jan 23 2019 09:05:05 GMT+0800 (CST) Resized terminal  s4b60hNpS  to  91  cols and  35  rows.
Wed Jan 23 2019 09:06:59 GMT+0800 (CST) Created terminal with PID: NA-hr0lgY
Wed Jan 23 2019 09:07:02 GMT+0800 (CST) Created terminal with PID: g9WtAgu5n
Wed Jan 23 2019 09:07:02 GMT+0800 (CST) Connected to terminal g9WtAgu5n
Wed Jan 23 2019 09:07:02 GMT+0800 (CST) Resized terminal  g9WtAgu5n  to  91  cols and  35  rows.
Wed Jan 23 2019 09:07:05 GMT+0800 (CST) Closed terminal g9WtAgu5n
/media/inkbox/software/software/electron/electerm-0.26.23-linux-x64/resources/app.asar/lib/dispatch-center.js:39
      let inst = global.sftpInsts[id]
                                 ^

TypeError: Cannot read property 'BDemIM3beHN' of undefined
    at WebSocket.ws.on (/media/inkbox/software/software/electron/electerm-0.26.23-linux-x64/resources/app.asar/lib/dispatch-center.js:39:34)
    at WebSocket.emit (events.js:187:15)
    at WebSocket.emitClose (/media/inkbox/software/software/electron/electerm-0.26.23-linux-x64/resources/app.asar/node_modules/ws/lib/websocket.js:172:10)
    at Socket.socketOnClose (/media/inkbox/software/software/electron/electerm-0.26.23-linux-x64/resources/app.asar/node_modules/ws/lib/websocket.js:781:15)
    at Socket.emit (events.js:182:13)
    at TCP._handle.close [as _onclose] (net.js:596:12)
Gtk-Message: 09:07:14.339: GtkDialog mapped without a transient parent. This is discouraged.


```

**Comment by zxdong262** [comment]
Released new version with bug fix. Thank you for the feedback!
