### ISSUE TITLE
"font/ttf" is an invalid MIME type ("font" is an unregistered media type)

### ISSUE THREAD

**Issue by pretendhigh** [electerm/electerm#1363]
## Operating system: CentOS Linux release 7.6.1810 (Core)
```
# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)
# gnome-shell --version
GNOME Shell 3.28.3
```
## Expected Behavior

About 5 mouth ago, I installed electerm-0.27.12-linux-x86_64 using the followed command.
```
# rpm -ivh electerm-0.27.12-linux-x86_64.rpm
```
It went ok. 
I think it should be ok to upgrade eleterm to 0.27.65-linux-x86_64 with command:
```
# rpm -ivh electerm-0.27.65-linux-x86_64.rpm
```

## Current Behavior

I uninstall electerm-0.27.12. But when I start to install electerm-0.27.65, there are some errors.
```
# rpm -e electerm-0.27.65-371.x86_64
# rpm -ivh electerm-0.27.65-linux-x86_64.rpm 
准备中...                          ################################# [100%]
正在升级/安装...
   1:electerm-0.27.65-371             ################################# [100%]
Error in file "/usr/share/applications/org.gnome.font-viewer.desktop": "font/ttf" is an invalid MIME type ("font" is an unregistered media type)
Error in file "/usr/share/applications/org.gnome.font-viewer.desktop": "font/otf" is an invalid MIME type ("font" is an unregistered media type)
```
I have tried to install electerm-0.27.63-linux-x86_64.rpm , But it had the same errors.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
How about the tar.gz release https://github.com/electerm/electerm/releases/download/v0.27.65/electerm-0.27.65-linux-x64.tar.gz, is it work? Can you try it?

**Comment by zxdong262** [comment]
I searched, is this related? https://bugzilla.redhat.com/show_bug.cgi?id=1564650

**Comment by pretendhigh** [comment]
+

> How about the tar.gz release https://github.com/electerm/electerm/releases/download/v0.27.65/electerm-0.27.65-linux-x64.tar.gz, is it work? Can you try it?
@zxdong262 
I try to use the electerm-0.27.65-linux-x64.tar.gz.  I run " ./electerm" command  when decompress the .tar.gz file because I can't find the icon on the destop.
```
# tar -zxvf electerm-0.27.65-linux-x64.tar.gz
$ cd tar -zxvf electerm-0.27.65-linux-x64.tar.gz
$ ./electerm 
[21984:0924/163424.097770:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /volumea/chrome_download/electerm-0.27.65-linux-x64/chrome-sandbox is owned by root and has mode 4755.
```
so I change chrome-sandbox mode 4755, and try "./electerm"  again. But there is a A JavaScript error .
```
# chmod 4755 chrome-sandbox
$ ./electerm 

(electerm:30721): Gtk-WARNING **: 16:49:51.150: Theme parsing error: gtk.css:4101:29: Expected ',' in color definition

(electerm:30721): Gtk-WARNING **: 16:49:51.150: Theme parsing error: gtk.css:4142:92: The :prelight pseudo-class is deprecated. Use :hover instead.

(electerm:30721): Gtk-WARNING **: 16:49:51.150: Theme parsing error: gtk.css:4146:43: The :prelight pseudo-class is deprecated. Use :hover instead.
16:49:51 › error parsing $HOME/.ssh/config
16:49:51 › maybe no $HOME/.ssh/config, but it is ok
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /volumea/chrome_download/electerm-0.27.65-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /volumea/chrome_download/electerm-0.27.65-linux-x64/resources/app.asar/node_modules/node-pty/lib/index.js
- /volumea/chrome_download/electerm-0.27.65-linux-x64/resources/app.asar/server/terminal.js
- /volumea/chrome_download/electerm-0.27.65-linux-x64/resources/app.asar/app.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/volumea/chrome_download/electerm-0.27.65-linux-x64/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/volumea/chrome_download/electerm-0.27.65-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/volumea/chrome_download/electerm-0.27.65-linux-x64/resources/app.asar/node_modules/node-pty/lib/index.js:13:20)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/volumea/chrome_download/electerm-0.27.65-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/volumea/chrome_download/electerm-0.27.65-linux-x64/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/volumea/chrome_download/electerm-0.27.65-linux-x64/resources/app.asar/server/terminal.js',
    '/volumea/chrome_download/electerm-0.27.65-linux-x64/resources/app.asar/app.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.y5Koy5)
    at process.func (electron/js2c/asar.js:155:31)
    at process.func [as dlopen] (electron/js2c/asar.js:155:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828:18)
    at Object.func (electron/js2c/asar.js:155:31)
    at Object.func [as .node] (electron/js2c/asar.js:164:18)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/volumea/chrome_download/electerm-0.27.65-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```

**Comment by pretendhigh** [comment]
> I searched, is this related? https://bugzilla.redhat.com/show_bug.cgi?id=1564650
@zxdong262 
Yes, it apper the same. But I don't know how to fix it. Maybe I will update my gnome someday.
```
# gnome-shell --version
GNOME Shell 3.28.3
# rpm -qa | grep desktop-file
desktop-file-utils-0.23-1.el7.x86_64
```

**Comment by zxdong262** [comment]
Have you try double click the electerm exe file from the electerm folder?

**Comment by pretendhigh** [comment]
> Have you try double click the electerm exe file from the electerm folder?
@zxdong262 
I'm using centos7 . There is no exe file under the electerm folder.

**Comment by zxdong262** [comment]
@pretendhigh I mean the file named `electerm`, double click it should run the app.

**Comment by pretendhigh** [comment]
> @pretendhigh I mean the file named `electerm`, double click it should run the app.
@zxdong262 
when I double click electerm file, It pops up a windows saying "could not display 'electerm'. There is no application installed for shared library file. Do you want to search an application to open this file".  Then I click yes to search the application and it tell me that "Additional MIME types required“

**Comment by zxdong262** [comment]
Sorry for delay, finally I got centos7 vm running, yes, rpm pack do not work, but after I uninstalled rmp pack, installed snap pack, it works, you may try it. @pretendhigh

**Comment by zxdong262** [comment]
Close it, feel free to reopen or submit another one if needed.
