### ISSUE TITLE
点击关闭报错

### ISSUE THREAD

**Issue by xiaoguanboy** [electerm/electerm#1382]
以下是弹出框报错信息
————————————————————————————————————
A JavaScript error occurred in the main process
Uncaught Exception:
Error: kill ESRCH
    at process.kill (internal/process/per_thread.js:188:13)
    at /Applications/electerm.app/Contents/Resources/app.asar/app.js:63:13
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
————————————————————————————————————
A JavaScript error occurred in the main process
 Uncaught Exception:
Error: kill ESRCH
    at process.kill (internal/process/per_thread.js:188:13)
    at /Applications/electerm.app/Contents/Resources/app.asar/app.js:63:13
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

**Comment by xiaoguanboy** [comment]
以上是mac版本

**Comment by xiaoguanboy** [comment]
0.27.72

**Comment by zxdong262** [comment]
Can not reproduce, close it for now
