### ISSUE TITLE
MacOS10.15 退出时报错

### ISSUE THREAD

**Issue by yangming1009** [electerm/electerm#1402]
Uncaught Exception:
Error: kill ESRCH
    at process.kill (internal/process/per_thread.js:188:13)
    at /Applications/electerm.app/Contents/Resources/app.asar/app.js:63:13
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

 版本:0.27.76

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/issues/1418
