### ISSUE TITLE
mac下链接超时重载后sfp本地文件目录一直加载中

### ISSUE THREAD

**Issue by mhlywxl** [electerm/electerm#1440]
## Current Behavior

刚连接时正常，但是连接超时重载后，本地目录一直加载中：

![image](https://user-images.githubusercontent.com/8207774/70207873-ee47b000-1766-11ea-9830-fd84d7247644.png)

远程的正常，就算新增一个本地的终端也是一直加载中：

![image](https://user-images.githubusercontent.com/8207774/70207914-17684080-1767-11ea-9943-93af39628847.png)

需要重启程序后才正常：

![image](https://user-images.githubusercontent.com/8207774/70207943-31098800-1767-11ea-803b-4eec4ac1ee19.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Seraphli** [comment]
确认这个问题在v0.27.100还存在, 通过重开electerm可以解决

**Comment by zxdong262** [comment]
可以看下log么，在关于面板最后一个tab

<img width="456" alt="Screen Shot 2019-12-25 at 10 36 45 AM" src="https://user-images.githubusercontent.com/1641949/71429620-83a0e900-2702-11ea-8f7a-aae0755e5704.png">

**Comment by Seraphli** [comment]
```
[2019-12-13 11:29:49.020] [info] no user config, but it is ok
[2019-12-13 11:29:49.145] [info] no ../../install-src file
[2019-12-13 11:29:49.145] [info] no install-src file
[2019-12-13 11:29:49.229] [info] no /Users/lichaoran/Library/Application Support/electerm-config.js but it is ok
[2019-12-13 11:29:49.229] [info] no /Users/lichaoran/Library/Application Support/electerm-user-config.json but it is ok
[2019-12-13 11:29:49.266] [info] no electerm-localstorage.json, but it is ok.
[2019-12-13 11:29:49.329] [info] no electerm-localstorage.json, but it is ok.
[2019-12-13 11:29:49.558] [info] no ../../install-src file
[2019-12-13 11:29:49.560] [info] no install-src file
[2019-12-13 11:29:49.577] [info] server runs on localhost 3075
[2019-12-13 11:32:15.297] [error] fs error ENOENT: no such file or directory, stat '/Users/lichaoran/Dockerfile'
[2019-12-13 18:23:39.038] [info] no ../../install-src file
[2019-12-13 18:23:39.039] [info] no install-src file
[2019-12-13 18:23:39.129] [info] no /Users/lichaoran/Library/Application Support/electerm-config.js but it is ok
[2019-12-13 18:23:39.509] [info] no ../../install-src file
[2019-12-13 18:23:39.512] [info] no install-src file
[2019-12-13 18:23:39.529] [info] server runs on localhost 3075
[2019-12-15 18:06:03.749] [info] no ../../install-src file
[2019-12-15 18:06:03.750] [info] no install-src file
[2019-12-15 18:06:03.887] [info] no /Users/lichaoran/Library/Application Support/electerm-config.js but it is ok
[2019-12-15 18:06:04.281] [info] no ../../install-src file
[2019-12-15 18:06:04.283] [info] no install-src file
[2019-12-15 18:06:04.298] [info] server runs on localhost 3075
[2019-12-18 15:04:29.709] [info] no ../../install-src file
[2019-12-18 15:04:29.712] [info] no install-src file
[2019-12-18 15:04:29.807] [info] no /Users/lichaoran/Library/Application Support/electerm-config.js but it is ok
[2019-12-18 15:04:30.233] [info] no ../../install-src file
[2019-12-18 15:04:30.235] [info] no install-src file
[2019-12-18 15:04:30.252] [info] server runs on localhost 3075
[2019-12-23 13:57:15.853] [error] errored terminal Error: Keepalive timeout
    at Timeout.sendKA (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:269:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2019-12-24 16:35:49.325] [info] no ../../install-src file
[2019-12-24 16:35:49.328] [info] no install-src file
[2019-12-24 16:35:49.423] [info] no /Users/lichaoran/Library/Application Support/electerm-config.js but it is ok
[2019-12-24 16:35:49.754] [info] no ../../install-src file
[2019-12-24 16:35:49.756] [info] no install-src file
[2019-12-24 16:35:49.770] [info] server runs on localhost 3075
[2019-12-24 16:38:51.150] [info] no ../../install-src file
[2019-12-24 16:38:51.152] [info] no install-src file
[2019-12-24 16:38:51.233] [info] no /Users/lichaoran/Library/Application Support/electerm-config.js but it is ok
[2019-12-24 16:38:51.309] [info] NaN NaN
[2019-12-24 16:38:51.574] [info] no ../../install-src file
[2019-12-24 16:38:51.576] [info] no install-src file
[2019-12-24 16:38:51.590] [info] server runs on localhost 3075
[2019-12-25 10:28:44.517] [info] no ../../install-src file
[2019-12-25 10:28:44.518] [info] no install-src file
[2019-12-25 10:28:44.600] [info] no /Users/lichaoran/Library/Application Support/electerm-config.js but it is ok
[2019-12-25 10:28:44.696] [info] 1342 847
[2019-12-25 10:28:44.987] [info] no ../../install-src file
[2019-12-25 10:28:44.990] [info] no install-src file
[2019-12-25 10:28:45.004] [info] server runs on localhost 3075
[2019-12-25 10:33:58.961] [error] ws send error
[2019-12-25 10:33:58.964] [error] Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ws/lib/websocket.js:314:19)
    at WebSocket.ws.s (/Applications/electerm.app/Contents/Resources/app.asar/server/dispatch-center.js:23:10)
    at /Applications/electerm.app/Contents/Resources/app.asar/server/transfer.js:36:10
    at invokeFunc (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:10333:23)
    at trailingEdge (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:10382:18)
    at Timeout.timerExpired [as _onTimeout] (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/lodash/lodash.js:10370:18)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)

```

**Comment by zxdong262** [comment]
Fixed now
