### ISSUE TITLE
 errored terminal Error: Timed out while waiting for handshake     at Timeout._onTimeout 

### ISSUE THREAD

**Issue by 284330505** [electerm/electerm#1442]
[2019-12-06 19:54:45.214] [error] errored terminal Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:698:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2019-12-06 20:04:18.237] [info] no ../../install-src file
[2019-12-06 20:04:18.238] [info] no install-src file
[2019-12-06 20:04:18.324] [info] no /Users/pc/Library/Application Support/electerm-config.js but it is ok
[2019-12-06 20:04:18.593] [info] no ../../install-src file
[2019-12-06 20:04:18.596] [info] no install-src file
[2019-12-06 20:04:18.635] [info] server runs on localhost 3075

**Comment by zxdong262** [comment]
Just cannot connect or timeout, can you try set longer timeout, or test in other ssh client.

**Comment by 284330505** [comment]
感谢你的回答，这个问题是因为我设置SSH/SFTP超时时间太长导致的

**Comment by 284330505** [comment]
Thanks for your answer. This question is caused by my setting SSH/SFTP timeout for too long

**Comment by 284330505** [comment]
Thanks for your answer. This question is caused by my setting SSH/SFTP timeout for too long
