### ISSUE TITLE
不支持多重认证

### ISSUE THREAD

**Issue by panxiaoguang** [electerm/electerm#1520]
如果集群或者服务器除了需要输入密码，还需要输入认证密钥，就无法链接，一直显示输入密码。
例如，我这个集群需要使用FreeOTP生成的动态口令才能登陆成功，本软件好像不支持

**Comment by zxdong262** [comment]
确实不支持，我不知道这种情形传回的提示或者数据是什么样的。

**Comment by panxiaoguang** [comment]
![](https://cdn.jsdelivr.net/gh/panxiaoguang/MyImage/img/20200108145917.png)
如图所示，登陆首先需要填入`password`,然后是`verification code`。例如xshell软件在登陆的时候，会直接将这些信息生成一个弹出框让用户输入（因为是动态的不能提前设置）。

**Comment by zxdong262** [comment]
https://github.com/mscdex/ssh2/issues/862

**Comment by zxdong262** [comment]
可以发log来看看吗，关于面板有个log选项，点击reload log

<img width="631" alt="Screen Shot 2020-01-08 at 3 13 40 PM" src="https://user-images.githubusercontent.com/1641949/71957731-8256dc80-3229-11ea-9426-eb157e7e7ae2.png">

**Comment by panxiaoguang** [comment]
```bash
[2020-01-08 15:24:52.692] [error] errored terminal Error: All configured authentication methods failed
    at doNextAuth (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:416:17)
    at tryNextAuth (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:487:5)
    at SSH2Stream.onUSERAUTH_FAILURE (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:600:5)
    at SSH2Stream.emit (events.js:203:13)
    at parsePacket (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:3779:10)
    at SSH2Stream._transform (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:694:13)
    at SSH2Stream.Transform._read (_stream_transform.js:189:10)
    at SSH2Stream._read (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:418:12)
    at writeOrBuffer (_stream_writable.js:402:5)
    at SSH2Stream.Writable.write (_stream_writable.js:302:11)
    at Socket.ondata (_stream_readable.js:720:22)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
[2020-01-08 15:25:05.287] [error] errored terminal Error: All configured authentication methods failed
    at doNextAuth (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:416:17)
    at tryNextAuth (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:487:5)
    at SSH2Stream.onUSERAUTH_FAILURE (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/@electerm/ssh2/lib/client.js:600:5)
    at SSH2Stream.emit (events.js:203:13)
    at parsePacket (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:3779:10)
    at SSH2Stream._transform (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:694:13)
    at SSH2Stream.Transform._read (_stream_transform.js:189:10)
    at SSH2Stream._read (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/ssh2-streams/lib/ssh.js:253:15)
    at SSH2Stream.Transform._write (_stream_transform.js:177:12)
    at doWrite (_stream_writable.js:418:12)
    at writeOrBuffer (_stream_writable.js:402:5)
    at SSH2Stream.Writable.write (_stream_writable.js:302:11)
    at Socket.ondata (_stream_readable.js:720:22)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
```

**Comment by zxdong262** [comment]
我想我知道怎么做了，得验证一下，也许下周

**Comment by panxiaoguang** [comment]
> 我想我知道怎么做了，得验证一下，也许下周

大佬666

**Comment by davidxujiayang** [comment]
请问这个问题解决了嘛?我也遇到相似的问题。

**Comment by zxdong262** [comment]
还没有

**Comment by zxdong262** [comment]
--> #1526
