### ISSUE TITLE
electerm not start

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1536]
## Electerm version:
1.0.19
## Operating system(linux, macos, or windows7/8/10?):
Linux redhat 7
## Expected Behavior

should start electerm
## Current Behavior

electerm fail start
## Steps to Reproduce
Install rpm electerm

## Detailed Description
[sperez@oc3245805674 ~]$ electerm
09:37:13 › error parsing $HOME/.ssh/config
09:37:13 › maybe no $HOME/.ssh/config, but it is ok
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/electerm/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/electerm/resources/app.asar/server/session.js
- /opt/electerm/resources/app.asar/app.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7620:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/electerm/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/electerm/resources/app.asar/server/session.js',
    '/opt/electerm/resources/app.asar/app.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.wFIlWF)
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)

**Comment by saulperez2905** [comment]
Hi
any update?

**Comment by saulperez2905** [comment]
@zxdong262 please need your help

**Comment by zxdong262** [comment]
@saulperez2905 Can you try the .gz pack: https://github.com/electerm/electerm/releases/download/v1.0.19/electerm-1.0.19-linux-x64.tar.gz

or snap pack: https://github.com/electerm/electerm/releases/download/v1.0.19/electerm-1.0.19-linux-amd64.snap

**Comment by zxdong262** [comment]
merge to #1538
