### ISSUE TITLE
点击设定同步 报错

### ISSUE THREAD

**Issue by wang628625** [electerm/electerm#1537]
Error: Request failed with status code 404
    at createError (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:208:15)
    at endReadableNT (_stream_readable.js:1168:12)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

**Comment by wang628625** [comment]
token 和gist id 都生成了

**Comment by wang628625** [comment]
嗯  已经好了 创建token的时候忘记勾选下面的属性了 谢谢

**Comment by PaTTeeL** [comment]
> 嗯 已经好了 创建token的时候忘记勾选下面的属性了 谢谢

我也碰到一样的问题了，看是不是可以在https://github.com/electerm/electerm/wiki/Create-personal-access-token这里强调token的权限里必须要勾选 gist 这一项，不然同步就会失败。
另外同步能不能增加一个发现配置修改后自动上传的功能？配置有改动就传上去，到时候有问题可以用gist管理配置文件的版本。

**Comment by zxdong262** [comment]
> > 嗯 已经好了 创建token的时候忘记勾选下面的属性了 谢谢
> 
> 我也碰到一样的问题了，看是不是可以在[https://github.com/electerm/electerm/wiki/Create-personal-access-token这里强调token的权限里必须要勾选](https://github.com/electerm/electerm/wiki/Create-personal-access-token%E8%BF%99%E9%87%8C%E5%BC%BA%E8%B0%83token%E7%9A%84%E6%9D%83%E9%99%90%E9%87%8C%E5%BF%85%E9%A1%BB%E8%A6%81%E5%8B%BE%E9%80%89) gist 这一项，不然同步就会失败。 另外同步能不能增加一个发现配置修改后自动上传的功能？配置有改动就传上去，到时候有问题可以用gist管理配置文件的版本。

wiki里加粗了
