### ISSUE TITLE
electerm does not start

### ISSUE THREAD

**Issue by saulperez2905** [electerm/electerm#1538]
## Electerm version:
1.0.19
## Operating system(linux, macos, or windows7/8/10?):
RedHat 7
## Expected Behavior

start electerm
## Current Behavior

many errors
## Steps to Reproduce
1) download electerm for linux
2) extract electerm
3) execute ./electerm
but show error:
[sperez@oc1178881380 electerm-1.0.19-linux-x64]$ ./electerm 
[11987:0128/141044.758036:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/sperez/Downloads/electerm-1.0.19-linux-x64/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
[sperez@oc1178881380 electerm-1.0.19-linux-x64]$ 

4) execute ./electerm --no-sandbox

[sperez@oc1178881380 electerm-1.0.19-linux-x64]$ 
[sperez@oc1178881380 electerm-1.0.19-linux-x64]$ ./electerm --no-sandbox
14:11:34 › error parsing $HOME/.ssh/config
14:11:34 › maybe no $HOME/.ssh/config, but it is ok
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /home/sperez/Downloads/electerm-1.0.19-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /home/sperez/Downloads/electerm-1.0.19-linux-x64/resources/app.asar/node_modules/node-pty/lib/index.js
- /home/sperez/Downloads/electerm-1.0.19-linux-x64/resources/app.asar/server/session.js
- /home/sperez/Downloads/electerm-1.0.19-linux-x64/resources/app.asar/app.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7620:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/sperez/Downloads/electerm-1.0.19-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/sperez/Downloads/electerm-1.0.19-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/home/sperez/Downloads/electerm-1.0.19-linux-x64/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/home/sperez/Downloads/electerm-1.0.19-linux-x64/resources/app.asar/server/session.js',
    '/home/sperez/Downloads/electerm-1.0.19-linux-x64/resources/app.asar/app.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.Rmd27Q)
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:922:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/sperez/Downloads/electerm-1.0.19-linux-x64/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)

**Comment by zxdong262** [comment]
As I tested, snap works, you may try it. I do not know why rpm/gz pack  do not work in redhat/centos etc...

**Comment by saulperez2905** [comment]
Hi
could you tell me how to execute snap

**Comment by zxdong262** [comment]
Snap install:

https://snapcraft.io/docs/installing-snapd

After installing, just `sudo snap install xxx.snap`

**Comment by zxdong262** [comment]
Close it now, feel free to open it if needed
