### ISSUE TITLE
通过书签连接的堡垒机服务器超时退出，另几点建议

### ISSUE THREAD

**Issue by c26411** [electerm/electerm#1570]
## Operating system(linux, macos, or windows7/8/10?):
mac os   windows 10  一样

1. 建议增加快速命令文件夹分类功能，满足不同的用途分类
2. 建议增加cmd+t （ctrl+t）快捷键快速新建连接
3. 建议增加日志记录功能
4. 建议通过新建连接的服务器名称同步修改标签的新建连接名称，方便阅读，不然多个标签都是新建连接，无法分辨，类似iterm2
5. 通过新建连接服务器后，无法使用zmodem协议的rzsz功能，书签连接的正常
6. **通过书签连接的堡垒机服务器超时退出（猜测是因为书签连接的含有sftp功能，由于通过堡垒机连接的服务器无法使用sftp功能，导致超时，如是这样，建议书签设置里，提供关闭sftp功能开关）**

附报错日志

```
[2020-02-23 23:20:06.920] [error] errored terminal Error: Timed out while waiting for handshake
    at Timeout._onTimeout (D:\electerm-1.0.28-win-x64\electerm-1.0.28-win-x64\resources\app.asar\node_modules\@electerm\ssh2\lib\client.js:698:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2020-02-23 23:20:29.697] [error] Error: (SSH) Channel open failure: open failed
    at file:///D:/electerm-1.0.28-win-x64/electerm-1.0.28-win-x64/resources/app.asar/assets/js/electerm.1.0.28-1b65f839d8c54b2f00215bbe547966b5161e4d52.js:19:241609
    at WebSocket.n (file:///D:/electerm-1.0.28-win-x64/electerm-1.0.28-win-x64/resources/app.asar/assets/js/electerm.1.0.28-1b65f839d8c54b2f00215bbe547966b5161e4d52.js:19:198637)
[2020-02-23 23:20:45.349] [error] errored terminal Error: Timed out while waiting for handshake
    at Timeout._onTimeout (D:\electerm-1.0.28-win-x64\electerm-1.0.28-win-x64\resources\app.asar\node_modules\@electerm\ssh2\lib\client.js:698:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2020-02-23 23:20:46.364] [error] errored terminal Error: Timed out while waiting for handshake
    at Timeout._onTimeout (D:\electerm-1.0.28-win-x64\electerm-1.0.28-win-x64\resources\app.asar\node_modules\@electerm\ssh2\lib\client.js:698:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2020-02-23 23:20:58.408] [error] fs error ENOENT: no such file or directory, open 'C:\Users\admin\AppData\Roaming\electerm\log.old.log'

```

**Comment by zxdong262** [comment]
5. 非书签的终端，调用的就是本地终端，如果rzsz不可用，那就是本地终端不支持
6. sftp和terminal共用session，如果连不上就是连不上，我也不知道堡垒机是有什么特别的地方，因为没有资源测试，另外一个用户也跟我说过这个问题。

**Comment by hope250** [comment]
赞同【6】希望可以给出设置，某些连接不启用SFTP。

**Comment by lonnywong** [comment]
@c26411 【5】可以试试 trzsz ( trz / tsz ) ，和 rz / sz 类似，并且支持 tmux。electerm 升级到 1.19 以上，服务端安装 trzsz ：https://github.com/trzsz/trzsz

**Comment by zxdong262** [comment]
可以试试keepalive interval设为0
