### ISSUE TITLE
新版本通过连接跳板机报如下错误

### ISSUE THREAD

**Issue by ShingmoYeung** [electerm/electerm#1602]
No Such File
Error: No Such File
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.2.2-42a49cbb715fa4391eb9118c1577bc8e47122c5c.js:19:414932
    at WebSocket.n (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.2.2-42a49cbb715fa4391eb9118c1577bc8e47122c5c.js:19:371960)

**Comment by zxdong262** [comment]
-> #1590
