### ISSUE TITLE
Gist setting sync failure "Request failed with status code 422"

### ISSUE THREAD

**Issue by em-winterschon** [electerm/electerm#1622]
## Operating system(linux, macos, or windows7/8/10?):
CentOS Linux 8.1, x86_64, RPM

## Expected Behavior
Settings should sync via gist with valid gistid + token. 

## Current Behavior
Sync fails with error 422.

```
LastSyncTime: -
Request failed with status code 422
Error: Request failed with status code 422
    at createError (/opt/electerm/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/electerm/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/electerm/resources/app.asar/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

## Possible Solution
N/A 

## Steps to Reproduce
1. Install version 1.3.2
2. Go to settings panel -> Settings Sync
3. Create new gistid according to instructions
4. Create new personal access token according to instructions
5. Click save
6. Click upload settings

#### Env
```
node:12.13.0
v8:8.0.426.26-electron.0
uv:1.32.0
zlib:1.2.11
brotli:1.0.7
ares:1.15.0
modules:76
nghttp2:1.39.2
napi:5
llhttp:1.1.4
http_parser:2.8.0
openssl:1.1.0
icu:65.1
unicode:12.1
electron:8.1.1
chrome:80.0.3987.141
```

#### Log
```
[2020-03-23 05:13:29.486] [info] no ../../install-src file
[2020-03-23 05:13:29.984] [info] no ../../install-src file
[2020-03-23 05:13:29.998] [info] server runs on localhost 3075
[2020-03-23 05:13:31.092] [info] dbVersion 0.0.0
[2020-03-23 05:13:31.093] [info] start: init db
[2020-03-23 05:13:31.116] [info] end: init db
[2020-03-23 05:13:31.119] [info] upgrade db version to 1.3.2
[2020-03-23 05:21:56.442] [error] Error: Request failed with status code 422
    at createError (/opt/electerm/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/opt/electerm/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/opt/electerm/resources/app.asar/node_modules/axios/lib/adapters/http.js:237:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

#### Dependencies
```
@electerm/electerm-locales:0.7.1
@electerm/ssh2:0.8.10
bluebird:3.7.2
body-parser:1.19.0
cors:2.8.5
electron-log:3.0.6
express:4.17.1
express-ws:4.0.0
find-free-port:2.0.0
font-list:1.2.6
gist-wrapper:0.1.0
json-deep-copy:1.1.1
lodash:4.17.15
nedb:1.8.0
node-pty:0.9.0
os-locale:4.0.0
path-validation:0.2.3
phin:3.4.1
react:16.13.0
react-dom:16.13.0
recursive-assign:0.2.0
serialport:8.0.7
shortid:2.2.15
socks:2.3.3
ssh-config:4.0.2
zmodem.js:0.1.9
```

## Context (Environment)
Can't sync settings with github gist

## Detailed Description
N/A

## Suggestions?
N/A

**Comment by zxdong262** [comment]
Thank you for the feedback, I think the latest release fixed this.
