### ISSUE TITLE
新建串口连接崩溃

### ISSUE THREAD

**Issue by Ernest-su** [electerm/electerm#1799]
## Electerm version:
1.3.55
## Operating system(linux, macos, or windows7/8/10?):
win10
## Expected Behavior
能够正常添加串口连接

## Steps to Reproduce
1. 点击设置
2. 点击书签
3. 点击serial
4. 页面崩溃，出现下面的信息
```
this.findBookmarkGroupId is not a function
TypeError: this.findBookmarkGroupId is not a function at eu.renderCommon (file:///D:/greenSoft/electerm-1.3.55-win-x64/resources/app.asar/assets/js/electerm.1.3.55-8d4d5257a10bf6377f4e137074fe167cfcd484a3.js:287:539234) at eu.renderTabs (file:///D:/greenSoft/electerm-1.3.55-win-x64/resources/app.asar/assets/js/electerm.1.3.55-8d4d5257a10bf6377f4e137074fe167cfcd484a3.js:287:541722) at eu.render (file:///D:/greenSoft/electerm-1.3.55-win-x64/resources/app.asar/assets/js/electerm.1.3.55-8d4d5257a10bf6377f4e137074fe167cfcd484a3.js:287:542017) at Ie (file:///D:/greenSoft/electerm-1.3.55-win-x64/resources/app.asar/node_modules/react-dom/umd/react-dom.production.min.js?1.3.55-8d4d5257a10bf6377f4e137074fe167cfcd484a3:104:8) at rh (file:///D:/greenSoft/electerm-1.3.55-win-x64/resources/app.asar/node_modules/react-dom/umd/react-dom.production.min.js?1.3.55-8d4d5257a10bf6377f4e137074fe167cfcd484a3:103:334) at zj (file:///D:/greenSoft/electerm-1.3.55-win-x64/resources/app.asar/node_modules/react-dom/umd/react-dom.production.min.js?1.3.55-8d4d5257a10bf6377f4e137074fe167cfcd484a3:228:490) at Th (file:///D:/greenSoft/electerm-1.3.55-win-x64/resources/app.asar/node_modules/react-dom/umd/react-dom.production.min.js?1.3.55-8d4d5257a10bf6377f4e137074fe167cfcd484a3:152:223) at tj (file:///D:/greenSoft/electerm-1.3.55-win-x64/resources/app.asar/node_modules/react-dom/umd/react-dom.production.min.js?1.3.55-8d4d5257a10bf6377f4e137074fe167cfcd484a3:152:152) at Te (file:///D:/greenSoft/electerm-1.3.55-win-x64/resources/app.asar/node_modules/react-dom/umd/react-dom.production.min.js?1.3.55-8d4d5257a10bf6377f4e137074fe167cfcd484a3:146:151) at file:///D:/greenSoft/electerm-1.3.55-win-x64/resources/app.asar/node_modules/react-dom/umd/react-dom.production.min.js?1.3.55-8d4d5257a10bf6377f4e137074fe167cfcd484a3:61:68
```

**Comment by zxdong262** [comment]
感谢反馈~
