### ISSUE TITLE
登陆 JumpServer 时会有错误提示信息

### ISSUE THREAD

**Issue by bb7788** [electerm/electerm#1838]
## Electerm version:
v1.5.7

## Operating system(linux, macos, or windows7/8/10?):
macOS Catalina

## Expected Behavior

登陆 JumpServer 的时候会有个错误提示信息
[截图](https://i.loli.net/2020/09/30/thpbzR7xWQvduJo.png)
错误信息：
please select one of the assets
Error: please select one of the assets
    at file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.5.7-a4616219953c450a34fa243051c654f82d18e8d0.js:291:424202
    at WebSocket.n (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.1.5.7-a4616219953c450a34fa243051c654f82d18e8d0.js:291:398898)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
应该是不能正确处理jumpserver的提示

**Comment by 5sdba** [comment]
+1

**Comment by zhucuiding** [comment]
这个问题还没修复吗

**Comment by zxdong262** [comment]
试试最新版
