### ISSUE TITLE
sftp error Failure

### ISSUE THREAD

**Issue by NOboys** [electerm/electerm#1960]
## Electerm version:
v1.10.9
## Operating system(linux, macos, or windows7/8/10?):
windows10
## Current Behavior

登陆堡垒机后，右下角一直提示 错误,查看日志显示如下
[2020-12-08 16:54:33.991] [debug] connect ETIMEDOUT XXX.XXX.XXX.XXX:XXXX fetch err info
[2020-12-08 17:09:22.547] [error] fetch error {
  message: 'timeout of 15000ms exceeded',
  name: 'Error',
  stack: 'Error: timeout of 15000ms exceeded\n' +
    '    at createError (D:\\landeTools\\xmannage\\anyting_replace\\electerm-1.10.9-win-x64\\resources\\app.asar\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n' +
    '    at RedirectableRequest.handleRequestTimeout (D:\\landeTools\\xmannage\\anyting_replace\\electerm-1.10.9-win-x64\\resources\\app.asar\\node_modules\\axios\\lib\\adapters\\http.js:264:16)\n' +
    '    at Object.onceWrapper (events.js:312:28)\n' +
    '    at RedirectableRequest.emit (events.js:223:5)\n' +
    '    at Timeout._onTimeout (D:\\landeTools\\xmannage\\anyting_replace\\electerm-1.10.9-win-x64\\resources\\app.asar\\node_modules\\follow-redirects\\index.js:166:13)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)',
  config: {
    url: 'https://electerm.github.io/electerm/version.html?_=1607418547540',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36'
    },
    transformRequest: [ null ],
    transformResponse: [ null ],
    timeout: 15000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    action: 'get-update-info',
    method: 'get'
  },
  code: 'ECONNABORTED'
}

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Veng0923** [comment]
我也碰到了这个问题！远程的没有ftp，但是我在设置里吧sftp关了，但是依旧报错，终端卡死！！！
[2020-12-08 19:04:49.410] [error] Error: Received exit code 127 while establishing SFTP session
    at file:///opt/electerm/resources/app.asar/assets/js/electerm.js?1.10.0:2:367070
    at WebSocket.n (file:///opt/electerm/resources/app.asar/assets/js/electerm.js?1.10.0:2:297580)
[2020-12-08 19:05:43.148] [debug] veng@veng-PC: /home/veng title change
[2020-12-08 19:05:43.150] [debug] veng@veng-PC: ~ title change
[2020-12-08 19:05:46.694] [error] fetch error {
  message: 'Timed out while waiting for handshake',
  stack: 'Error: Timed out while waiting for handshake\n' +
    '    at Timeout._onTimeout (/opt/electerm/resources/app.asar/node_modules/ssh2/lib/client.js:695:19)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}
[2020-12-08 19:05:46.696] [debug] { message: 'Timed out while waiting for handshake' }
[2020-12-08 19:05:46.697] [debug] Timed out while waiting for handshake fetch err info
[2020-12-08 19:06:13.702] [error] fetch error {
  message: 'Timed out while waiting for handshake',
  stack: 'Error: Timed out while waiting for handshake\n' +
    '    at Timeout._onTimeout (/opt/electerm/resources/app.asar/node_modules/ssh2/lib/client.js:695:19)\n' +
    '    at listOnTimeout (internal/timers.js:531:17)\n' +
    '    at processTimers (internal/timers.js:475:7)'
}

**Comment by zxdong262** [comment]
试试最新版
