### ISSUE TITLE
版本更新后无法连接服务器

### ISSUE THREAD

**Issue by jiabintang** [electerm/electerm#2028]
测试连接显示
connection fails: Cannot read property's' of undefined

**Comment by zxdong262** [comment]
方便提供更详细的信息吗 包括版本，操作系统，等等

**Comment by pastcloud** [comment]
我也出现同样的问题，mac big sur系统，在软件1.11之后的版本就会出现这样的问题，mac-arm64安装后无法运行，无arm64版本会报connection fails: Cannot read property's' of undefined这个错，v1.10.39目前可正常使用，而且在big sur系统上现在感觉到明显的卡顿

**Comment by leonunix** [comment]
Cannot set property 'onclose' of undefined
TypeError: Cannot set property 'onclose' of undefined at xt (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.11.5:2:305419) at async St (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.11.5:2:305519) at async $o.localList (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.11.5:2:412089)

一样的问题

**Comment by jiabintang** [comment]
mac big sur系统，在软件1.11之后 mac-arm64

**Comment by zxdong262** [comment]
@jiabintang  @leonunix 
arm64目前不可用，构建未见报错，但是运行就会报错, 我还不知道原因，也没有m1设备，不能测试, vscode已经发布ARM64版本，所以肯定是可以的，只是我没有搞定.

**Comment by leonunix** [comment]
@zxdong262 
我用的是intel的mac book pro 升级1.11以后。会有上述的错误。OS版本是10.14.6

**Comment by zxdong262** [comment]
@leonunix 可以命令行运行`/Applications/electerm.app/Contents/MacOS/electerm`看看输出吗？

**Comment by leonunix** [comment]
@zxdong262 
问题有点复杂，感觉是ssh协议的问题。
我有2台服务器。一台是比较老的solaris。一台是比较新的solaris。2台支持的ssh协议不一样。
情况是这样的。启动app。连接老的solaris。连接失败。再开新的窗口连接任何服务器，都报connection fails: Cannot read property's' of undefined错误。
启动app 。连接新的solaris、没有任何问题。这时候如果再连接老的solaris。整个electerm进去上面的情况。
命令行运行/Applications/electerm.app/Contents/MacOS/electerm没有任何错误的输出。

**Comment by zxdong262** [comment]
@leonunix 确实像是协议问题，两台用的什么ssh-server呢？

**Comment by leonunix** [comment]
@zxdong262 类似centos6和centos7的区别openssl库不一样。

**Comment by zxdong262** [comment]
@leonunix 之前的版本也是这样的情况吗，比如1.10.14?

**Comment by leonunix** [comment]
@zxdong262 1.11以后版本才有这个问题。之前的版本没有问题。

**Comment by hezongkun** [comment]
`catcher@hezongkundeMBP ~ % /Applications/electerm.app/Contents/MacOS/electerm
20:05:08 debug › electerm start
(node:64262) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/index.js
- /Applications/electerm.app/Contents/Resources/app.asar/server/session.js
- /Applications/electerm.app/Contents/Resources/app.asar/server/dispatch-center.js
- /Applications/electerm.app/Contents/Resources/app.asar/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:31:15)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/index.js',
    '/Applications/electerm.app/Contents/Resources/app.asar/server/session.js',
    '/Applications/electerm.app/Contents/Resources/app.asar/server/dispatch-center.js',
    '/Applications/electerm.app/Contents/Resources/app.asar/server/server.js'
  ]
}
/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:36
        throw outerError;
        ^

Error: dlopen(/var/folders/b1/qs9nv66160155msv9w8lc3mw0000gn/T/.org.chromium.Chromium.8jz0OH, 1): no suitable image found.  Did find:
	/var/folders/b1/qs9nv66160155msv9w8lc3mw0000gn/T/.org.chromium.Chromium.8jz0OH: mach-o, but wrong architecture
	/var/folders/b1/qs9nv66160155msv9w8lc3mw0000gn/T/.org.chromium.Chromium.8jz0OH: stat() failed with errno=17
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
`
m1 运行卡在启动界面，以上为启动log

**Comment by zxdong262** [comment]
最新版应该可以了
