### ISSUE TITLE
M1  无法运行

### ISSUE THREAD

**Issue by 4860575** [electerm/electerm#2032]
## Electerm version:
1.11.5
## Operating system(linux, macos, or windows7/8/10?):
macOS M1
## Steps to Reproduce

1.
2.
3.
4.

## Detailed Description

21:38:08 debug › electerm start
(node:12658) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/index.js
- /Applications/electerm.app/Contents/Resources/app.asar/server/session.js
- /Applications/electerm.app/Contents/Resources/app.asar/server/dispatch-center.js
- /Applications/electerm.app/Contents/Resources/app.asar/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:31:15)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/index.js',
    '/Applications/electerm.app/Contents/Resources/app.asar/server/session.js',
    '/Applications/electerm.app/Contents/Resources/app.asar/server/dispatch-center.js',
    '/Applications/electerm.app/Contents/Resources/app.asar/server/server.js'
  ]
}
/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:36
        throw outerError;
        ^

Error: dlopen(/var/folders/z3/jn18x6rj1dz154qyjrt0ml2h0000gn/T/.org.chromium.Chromium.NQidAh, 1): no suitable image found.  Did find:
	/var/folders/z3/jn18x6rj1dz154qyjrt0ml2h0000gn/T/.org.chromium.Chromium.NQidAh: mach-o, but wrong architecture
	/var/folders/z3/jn18x6rj1dz154qyjrt0ml2h0000gn/T/.org.chromium.Chromium.NQidAh: stat() failed with errno=17
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)

**Comment by zxdong262** [comment]
合并到--> #2009
