### ISSUE TITLE
在macbook pro 没

### ISSUE THREAD

**Issue by kelvenlaw** [electerm/electerm#2044]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Expected Behavior

启动成功
## Current Behavior

一直停留在系统启动画面，无法正常启动。
![image](https://user-images.githubusercontent.com/1327174/105619891-07f7fb00-5e32-11eb-8bac-1d552a848832.png)

## Possible Solution

底层出错
## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
可以命令行运行看看输出吗 `/Applications/electerm.app/Contents/MacOS/electerm`

**Comment by MapleGone** [comment]
`22:27:05 debug › electerm start
(node:16567) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/index.js
- /Applications/electerm.app/Contents/Resources/app.asar/server/session.js
- /Applications/electerm.app/Contents/Resources/app.asar/server/dispatch-center.js
- /Applications/electerm.app/Contents/Resources/app.asar/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:31:15)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/index.js',
    '/Applications/electerm.app/Contents/Resources/app.asar/server/session.js',
    '/Applications/electerm.app/Contents/Resources/app.asar/server/dispatch-center.js',
    '/Applications/electerm.app/Contents/Resources/app.asar/server/server.js'
  ]
}
/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:36
        throw outerError;
        ^

Error: dlopen(/var/folders/y4/31wn2nw55n704ylhpt0q79q00000gn/T/.org.chromium.Chromium.RdH3e9, 1): no suitable image found.  Did find:
	/var/folders/y4/31wn2nw55n704ylhpt0q79q00000gn/T/.org.chromium.Chromium.RdH3e9: mach-o, but wrong architecture
	/var/folders/y4/31wn2nw55n704ylhpt0q79q00000gn/T/.org.chromium.Chromium.RdH3e9: stat() failed with errno=17
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2039)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Applications/electerm.app/Contents/Resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)`

**Comment by MapleGone** [comment]
如上部分，好几个版本都是这个样子 @zxdong262

**Comment by zxdong262** [comment]
m1的本子？下载的arm版本？如果是下载mac-arm版本，那是暂时还不可用，我还没有build成功，可以试试普通版本
