### ISSUE TITLE
启动后无法正常进入软件

### ISSUE THREAD

**Issue by hope250** [electerm/electerm#2056]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Electerm version:
electerm-1.11.12-linux-amd64

## Operating system(linux, macos, or windows7/8/10?):
Deepin V20.1(1030)

## Expected Behavior

`$ electerm                                                                                                                                                   
10:20:30 debug › electerm start                                                                                                                                                  
innerError Error: Cannot find module '../build/Debug/pty.node'                                                                                                                   
Require stack:                                                                                                                                                                   
- /opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js                                                                                                     
- /opt/electerm/resources/app.asar/node_modules/node-pty/lib/index.js                                                                                                            
- /opt/electerm/resources/app.asar/server/session.js                                                                                                                             
- /opt/electerm/resources/app.asar/server/dispatch-center.js                                                                                                                     
- /opt/electerm/resources/app.asar/server/server.js                                                                                                                              
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:17)                                                                                                  
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/electerm/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/electerm/resources/app.asar/server/session.js',
    '/opt/electerm/resources/app.asar/server/dispatch-center.js',
    '/opt/electerm/resources/app.asar/server/server.js'
  ]
}
/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: /tmp/.org.chromium.Chromium.pL61bw: invalid ELF header
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:967:30)`

**Comment by zxdong262** [comment]
请问用的.dep还是snap或者tar.gz?

**Comment by zxdong262** [comment]
我试了下ubuntu20.04 .deb可以

**Comment by hope250** [comment]
> 请问用的.deb还是snap或者tar.gz?

deb

**Comment by hope250** [comment]
> 我试了下ubuntu20.04 .deb可以

重新安装 1.11.11.1 可以正常使用

**Comment by zxdong262** [comment]
@hope250 可以试试1.11.13吗

**Comment by hope250** [comment]
> @hope250 可以试试1.11.13吗

1.11.13 之后的版本可以正常使用。
