### ISSUE TITLE
snap安装v1.12.2之后都是卡在启动图

### ISSUE THREAD

**Issue by 1138331845** [electerm/electerm#2101]
## Please check known issues first

https://github.com/electerm/electerm/wiki/Know-issues

## Steps to Reproduce

1.
2.
3.
4.

**Comment by zxdong262** [comment]
什么操作系统，具体哪个版本呢，最新版也是吗？方便命令行启动看看报什么错误吗?

**Comment by 1138331845** [comment]
manjaro v1.12.2之后的版本都这样，包括最新版

**Comment by 1138331845** [comment]
error: unknown option '--no-sandbox'
23:22:33 debug › electerm start
Gtk-Message: 23:22:33.360: Failed to load module "xapp-gtk3-module"
Gtk-Message: 23:22:33.383: Failed to load module "colorreload-gtk-module"
Gtk-Message: 23:22:33.383: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 23:22:33.383: Failed to load module "appmenu-gtk-module"
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/index.js
- /snap/electerm/133/resources/app.asar/server/session.js
- /snap/electerm/133/resources/app.asar/server/dispatch-center.js
- /snap/electerm/133/resources/app.asar/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/snap/electerm/133/resources/app.asar/server/session.js',
    '/snap/electerm/133/resources/app.asar/server/dispatch-center.js',
    '/snap/electerm/133/resources/app.asar/server/server.js'
  ]
}
/snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /run/user/1000/snap.electerm/.org.chromium.Chromium.SPgyKq)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)

**Comment by oliver-lin** [comment]
卡启动界面+1，系统majaro

**Comment by zxdong262** [comment]
确实snap的包有问题, 我在ubuntu试了下deb和tar.gz的包是可以的

**Comment by zxdong262** [comment]
目前我也不知道是什么原因

**Comment by MasterOfStar** [comment]
Ubuntu 20.04
snap install electerm
同样有问题

$ electerm
error: unknown option '--no-sandbox'
11:14:11 debug › electerm start

(electerm:10076): Gtk-WARNING **: 11:14:11.311: Theme parsing error: gtk.css:1566:23: 'font-feature-settings' is not a valid property name

(electerm:10076): Gtk-WARNING **: 11:14:11.320: Theme parsing error: gtk.css:3616:25: 'font-feature-settings' is not a valid property name

(electerm:10076): Gtk-WARNING **: 11:14:11.322: Theme parsing error: gtk.css:4078:23: 'font-feature-settings' is not a valid property name
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/index.js
- /snap/electerm/133/resources/app.asar/server/session.js
- /snap/electerm/133/resources/app.asar/server/dispatch-center.js
- /snap/electerm/133/resources/app.asar/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/snap/electerm/133/resources/app.asar/server/session.js',
    '/snap/electerm/133/resources/app.asar/server/dispatch-center.js',
    '/snap/electerm/133/resources/app.asar/server/server.js'
  ]
}
/snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:35
        throw outerError;
        ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /run/user/1000/snap.electerm/.org.chromium.Chromium.IQgcF2)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/snap/electerm/133/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (internal/modules/cjs/loader.js:967:30)

**Comment by liruipeng-a** [comment]
Ubuntu18.04 使用dpkg安装deb包后，卡在启动界面。
Ubuntu20.04 使用正常。

**Comment by zxdong262** [comment]
最新版解决了，是因为之前我使用20.4版本ubuntu构建导致的。 @1138331845 @liruipeng-a @MasterOfStar
