### ISSUE TITLE
Ubuntu18.04卡启动界面。

### ISSUE THREAD

**Issue by liruipeng-a** [electerm/electerm#2109]
# 启动日志 

17:13:44 debug › electerm start
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/electerm/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/electerm/resources/app.asar/server/session.js
- /opt/electerm/resources/app.asar/server/dispatch-center.js
- /opt/electerm/resources/app.asar/server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:31:15)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/electerm/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/electerm/resources/app.asar/server/session.js',
    '/opt/electerm/resources/app.asar/server/dispatch-center.js',
    '/opt/electerm/resources/app.asar/server/server.js'
  ]
}
/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:36
        throw outerError;
        ^

Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.KpiIAx)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1034:18)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/opt/electerm/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:27:11)
    at Module._compile (internal/modules/cjs/loader.js:967:30)

# 其中
## Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.KpiIAx)   
Ubuntu18.04 GLIBC版本为：**2.27**  

strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_PRIVATE
GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1.4) stable release version 2.27.

 **应该是这个原因导致卡启动界面**

**Comment by darrenliuwei** [comment]
Ubuntu18.04这也太老了吧

Ubuntu 21.04马上就要正式发布了

**Comment by zxdong262** [comment]
可以试试那个linux.tar.gz吗, 很遗憾这个问题我也不知道根本原因

**Comment by liruipeng-a** [comment]
> Ubuntu18.04这也太老了吧
> 
> Ubuntu 21.04马上就要正式发布了

工作环境就是这样，没办法改呀

**Comment by chenstin** [comment]
需要降electerm的版本，太新的不行。我Ubuntu18.04，使用v1.12.0版本。

**Comment by MasterOfStar** [comment]
centos同样卡启动界面 GLIBC依赖问题 应该是electerm的一些依赖对glibc2.28版本有需求

**Comment by colatea** [comment]
卡在启动页面 +1
██████████████████  ████████   colatea@colatea-manjaro 
██████████████████  ████████   ----------------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: 10S4S02L00 ThinkCentre M920x-N000 
████████            ████████   Kernel: 5.10.34-1-MANJARO 
████████  ████████  ████████   Uptime: 1 hour, 24 mins 
████████  ████████  ████████   Packages: 1463 (pacman), 18 (snap) 
████████  ████████  ████████   Shell: zsh 5.8 
████████  ████████  ████████   Resolution: 1920x1200 
████████  ████████  ████████   DE: GNOME 
████████  ████████  ████████   WM: Mutter 
████████  ████████  ████████   WM Theme: Matcha-dark-sea 
████████  ████████  ████████   Theme: Matcha-sea [GTK2/3] 
████████  ████████  ████████   Icons: Papirus-Dark-Maia [GTK2/3] 
                               Terminal: gnome-terminal 
                               CPU: Intel i5-9500 (6) @ 4.400GHz 
                               GPU: Intel UHD Graphics 630 
                               Memory: 3037MiB / 15846MiB

**Comment by zxdong262** [comment]
最新版应该解决了，是我之前用20.4构建导致的 @darrenliuwei @chenstin @MasterOfStar @colatea
