### ISSUE TITLE
添加快速命令出现报错

### ISSUE THREAD

**Issue by weihaipy** [electerm/electerm#2229]
```
Error: An object could not be cloned.
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73:503)
    at Object.runGlobalAsync (D:\bin\electerm\resources\app.asar\preload\preload.js:95:24)
    at ec (file:///INSTALL_DIR/electerm/resources/app.asar/assets/js/electerm.js?1.16.3:2:1586916)
    at nc (file:///INSTALL_DIR/electerm/resources/app.asar/assets/js/electerm.js?1.16.3:2:1587124)
    at Proxy.e.batchDbAdd (file:///INSTALL_DIR/electerm/resources/app.asar/assets/js/electerm.js?1.16.3:2:1714799)
    at Proxy.addItem (file:///INSTALL_DIR/electerm/resources/app.asar/assets/js/electerm.js?1.16.3:2:1723728)
    at onFinish (file:///INSTALL_DIR/electerm/resources/app.asar/assets/js/electerm.js?1.16.3:2:1623745)
    at onFinish (file:///INSTALL_DIR/electerm/resources/app.asar/assets/js/electerm.js?1.16.3:2:491878)
    at file:///INSTALL_DIR/electerm/resources/app.asar/assets/js/electerm.js?1.16.3:2:489708
```

**Comment by zxdong262** [comment]
感谢反馈
