### ISSUE TITLE
远程编辑时，路径中有空格导致异常

### ISSUE THREAD

**Issue by gadfly3173** [electerm/electerm#2318]
使用`编辑...`功能设置VS Code作为编辑器后，点击open无效，`renderer.log`出现错误日志：
```log
[2021-12-02 17:20:55.002] [error] fetch error {
  message: 'Command failed: C:\\Users\\24273\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe C:\\Users\\24273\\AppData\\Local\\Temp\\z23dNdK1MLC7yquPI_7dL.conf\n' +
    "'C:\\Users\\24273\\AppData\\Local\\Programs\\Microsoft' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n" +
    '���������ļ���\r\n',
  stack: 'Error: Command failed: C:\\Users\\24273\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe C:\\Users\\24273\\AppData\\Local\\Temp\\z23dNdK1MLC7yquPI_7dL.conf\n' +
    "'C:\\Users\\24273\\AppData\\Local\\Programs\\Microsoft' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���\r\n" +
    '���������ļ���\r\n' +
    '\n' +
    '    at ChildProcess.exithandler (child_process.js:317:12)\n' +
    '    at ChildProcess.emit (events.js:315:20)\n' +
    '    at maybeClose (internal/child_process.js:1048:16)\n' +
    '    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)'
}
```
在路径输入框中自行输入引号也无效。

路径带空格还是挺常见的，VS Code的默认安装路径也是带空格的
![image](https://user-images.githubusercontent.com/28685179/144394257-5601d33d-ce5e-4e08-9a00-01f9f2ec0510.png)

**Comment by gadfly3173** [comment]
依然无法使用vscode
```log
[2022-01-13 17:56:55.567] [error] fetch error {
  message: 'Command failed: "C:\\Users\\24273\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" "C:\\Users\\24273\\AppData\\Local\\Temp\\mrMNfFl59uB36qLrvGfbk.yml"\n',
  stack: 'Error: Command failed: "C:\\Users\\24273\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" "C:\\Users\\24273\\AppData\\Local\\Temp\\mrMNfFl59uB36qLrvGfbk.yml"\n' +
    '\n' +
    '    at ChildProcess.exithandler (child_process.js:317:12)\n' +
    '    at ChildProcess.emit (events.js:315:20)\n' +
    '    at maybeClose (internal/child_process.js:1048:16)\n' +
    '    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)'
}
[2022-01-13 17:57:06.084] [error] fetch error {
  message: 'Command failed: "C:\\Users\\24273\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" "C:\\Users\\24273\\AppData\\Local\\Temp\\_3kV-h6JY4haaV8rAl2wa.yml"\n',
  stack: 'Error: Command failed: "C:\\Users\\24273\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe" "C:\\Users\\24273\\AppData\\Local\\Temp\\_3kV-h6JY4haaV8rAl2wa.yml"\n' +
    '\n' +
    '    at ChildProcess.exithandler (child_process.js:317:12)\n' +
    '    at ChildProcess.emit (events.js:315:20)\n' +
    '    at maybeClose (internal/child_process.js:1048:16)\n' +
    '    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)'
```
