### ISSUE TITLE
删除书签时抛出异常

### ISSUE THREAD

**Issue by gengyang1986** [electerm/electerm#2320]
删除书签右下角弹框抛出异常 日志如下

`[2021-12-03 17:42:11.389] [error] Error: An object could not be cloned.
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73:503)
    at Object.runGlobalAsync (/Applications/electerm.app/Contents/Resources/app.asar/preload/preload.js:95:24)
    at el (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.17.19:2:1529782)
    at il (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.17.19:2:1530187)
    at Proxy.e.batchDbUpdate (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.17.19:2:1663158)
    at Proxy.delBookmarkGroup (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.17.19:2:1670103)
    at El.del (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.17.19:2:1536067)
    at onConfirm (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.17.19:2:1536838)
    at E (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.17.19:2:226572)
    at Q (file:///Applications/electerm.app/Contents/Resources/app.asar/assets/js/electerm.js?1.17.19:2:91796)`

## Electerm version:
1.17.19
## Operating system(linux, macos, or windows7/8/10?):
macos m1

**Comment by zxdong262** [comment]
可以试试最新版是不是修复了吗
