### ISSUE TITLE
App does not start on Win 10 with with Error> Error occurred in handler for 'async': TypeError: Cannot read properties of undefined (reading 'setMenu')

### ISSUE THREAD

**Issue by sinnfeinn** [electerm/electerm#2446]
### Electerm Version(Electerm版本)

1.21.18

### Platform detail (平台详情)

Microsoft Windows NT 10.0.19044.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

Starting the app shows this error when executed via CMD>
Error occurred in handler for 'async': TypeError: Cannot read properties of undefined (reading 'setMenu')
    at initApp (C:\Users\ggg\AppData\Local\Programs\electerm\resources\app.asar\lib\init-app.js:34:19)
    at Object.init (C:\Users\ggg\AppData\Local\Programs\electerm\resources\app.asar\lib\ipc.js:83:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node:electron/js2c/browser_init:193:563

### What should have happened?(期望的结果)

App should start.

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

No. Previous version (1.20.6) worked.

### Additional information(其他任何相关信息)

Error occurred in handler for 'async': TypeError: Cannot read properties of undefined (reading 'setMenu')
    at initApp (C:\Users\ggg\AppData\Local\Programs\electerm\resources\app.asar\lib\init-app.js:34:19)
    at Object.init (C:\Users\ggg\AppData\Local\Programs\electerm\resources\app.asar\lib\ipc.js:83:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node:electron/js2c/browser_init:193:563

**Comment by quintindunn** [comment]
Same thing happening to me.

**Comment by zxdong262** [comment]
fixed in 1.21.20
