### ISSUE TITLE
trz不能正常工作

### ISSUE THREAD

**Issue by xxoxx** [electerm/electerm#2964]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.30.9-mac-x64.dmg

### Platform detail (平台详情)

mac-x64.

### What steps will reproduce the bug?(重新问题的详细步骤)

trz 上传文件
报错:
[root@localhost tmp]# trz
TypeError: t.isFile is not a function
    at d2 (http://127.0.0.1:30974/js/electerm-1.30.9.js:9:748)
    at Oy (http://127.0.0.1:30974/js/electerm-1.30.9.js:9:1394)
    at Kk.<anonymous> (http://127.0.0.1:30974/js/electerm-1.30.9.js:16:5362)
    at Generator.next (<anonymous>)
    at a (http://127.0.0.1:30974/js/electerm-1.30.9.js:8:768)
goroutine 1 [running]:

### What should have happened?(期望的结果)

成功上传文件

**Comment by xxoxx** [comment]
<img width="1332" alt="图片" src="https://github.com/electerm/electerm/assets/8625218/91eaa564-5a35-41f6-bb4d-3a88be94a003">

**Comment by xxoxx** [comment]
之前修好了tsz， 现在trz又出问题了， 麻烦修复一下

**Comment by zxdong262** [comment]
感谢反馈~发布了新版本, 修复了这个问题
