### ISSUE TITLE
1.38.41 sftp上传覆盖文件失败

### ISSUE THREAD

**Issue by Ecalose** [electerm/electerm#3329]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.41-win-x64-installer.exe

### Platform detail (平台详情)

windows11

### What steps will reproduce the bug?(重新问题的详细步骤)

上传覆盖二进制文件wireproxy报错，报错信息如下:
```
at http://127.0.0.1:30975/js/electerm-1.38.41.js:86:15266
    at Object.resolve (http://127.0.0.1:30975/js/electerm-1.38.41.js:61:5317)
    at Worker.fp (http://127.0.0.1:30975/js/electerm-1.38.41.js:61:6209)
```

### What should have happened?(期望的结果)

上传成功

### Additional information(其他任何相关信息)

服务器为debian11

**Comment by Ecalose** [comment]
知道原因了，文件在被使用
