### ISSUE TITLE
连接远程windows 打开Sftp时候报错

### ISSUE THREAD

**Issue by HaoyuRuan** [electerm/electerm#3379]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.70-win-x64-portable.tar.gz

### Platform detail (平台详情)

 Microsoft Windows NT 10.0.22000.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

1、使用ssh 连接一个windows 远程服务器，远程服务器运行OS版本为windows 10
2、切换到SFTP 标签
3、软件报错 报错信息如下
No such file
Error: No such file at http://127.0.0.1:30975/js/electerm-1.38.70.js:86:16028 at Object.resolve (http://127.0.0.1:30975/js/electerm-1.38.70.js:61:5380) at Worker.xp (http://127.0.0.1:30975/js/electerm-1.38.70.js:61:6272)
远程栏 信息空白
 
4、此时 可以在远程 地址栏输入 例如 C:\  ，可以正常获取到远程的文件信息
5、sftp的功能是正常的。

### What should have happened?(期望的结果)

初始没有报错

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

否
使用filezilla 软件连接无此问题

### Additional information(其他任何相关信息)

No such file
Error: No such file at http://127.0.0.1:30975/js/electerm-1.38.70.js:86:16028 at Object.resolve (http://127.0.0.1:30975/js/electerm-1.38.70.js:61:5380) at Worker.xp (http://127.0.0.1:30975/js/electerm-1.38.70.js:61:6272)

**Comment by zxdong262** [comment]
目前sftp操作里有一些专属Linux命令，所以windows服务器下还不能完善支持
