### ISSUE TITLE
windows11 丢失连接

### ISSUE THREAD

**Issue by wzgdxg** [electerm/electerm#3384]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.70-win-x64-installer.exe

### Platform detail (平台详情)

windows 11

### What steps will reproduce the bug?(重新问题的详细步骤)

刚打开应用正常，只要操作，不久就会丢失连接。
而且一旦丢失连接了，那所有的连接标签全部都是连接，关闭所有标签再打开也不行，只能重新打开应用

有一次丢失报了如下错误：
Cannot read properties of undefined (reading 's')
TypeError: Cannot read properties of undefined (reading 's')
    at Vg.init (http://127.0.0.1:30975/js/electerm-1.38.70.js:86:15693)
    at async Yg (http://127.0.0.1:30975/js/electerm-1.38.70.js:86:16262)
    at async hw.remoteList (http://127.0.0.1:30975/js/electerm-1.38.70.js:89:9598)
    at async hw.initRemoteAll (http://127.0.0.1:30975/js/electerm-1.38.70.js:89:8098

### What should have happened?(期望的结果)

麻烦解决下连接丢失问题

**Comment by zxdong262** [comment]
可以试试最新版吗

**Comment by CNSukidayo** [comment]
> 可以试试最新版吗 https://github.com/electerm/electerm/releases/tag/v1.38.81

新版本(v1.38.81)依旧存在这个问题,我连接腾讯云一般登陆成功后5-10s就会断开连接,并且同样遇到了"一旦丢失连接了，那所有的连接标签全部都丢失连接，关闭所有标签再打开也不行，只能重新打开应用"的问题

**Comment by zxdong262** [comment]
可以试试 https://github.com/electerm/electerm/releases/tag/v1.38.86 吗
