### ISSUE TITLE
存在 OTP code 情况下 sftp 报错

### ISSUE THREAD

**Issue by FangPengbo** [electerm/electerm#3391]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.37.126-win-x64-installer.exe

### Platform detail (平台详情)

windows10

### What steps will reproduce the bug?(重新问题的详细步骤)

存在OTP code  情况下，连接的时候可以正常弹出输入框 输入code进行连接
连接成功之后点击 sftp的时候未弹出 输入otp code，而是直接右下角抛出了异常

please select one of the assets
Error: please select one of the assets
    at http://127.0.0.1:30974/js/electerm-1.37.126.js:144:16018
    at Object.resolve (http://127.0.0.1:30974/js/electerm-1.37.126.js:69:5320)
    at Worker.P0 (http://127.0.0.1:30974/js/electerm-1.37.126.js:69:6214)

### What should have happened?(期望的结果)

在点击sftp的时候也弹出 code 输入框

**Comment by zxdong262** [comment]
Fixed in latest release
