### ISSUE TITLE
便携版-删除时报错：sftp.list is not a function

### ISSUE THREAD

**Issue by langren1353** [electerm/electerm#3394]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.38.81-win-x64-portable.tar.gz

### Platform detail (平台详情)

Microsoft Windows NT 10.0.19044.0 x64

### What steps will reproduce the bug?(重新问题的详细步骤)

1.使用SFTP上传任意文件夹
2.删除该文件夹 - 同一用户，报错：sftp.list is not a function

Error: sftp.list is not a function
    at http://127.0.0.1:30975/js/electerm-1.38.81.js:86:16028
    at Object.resolve (http://127.0.0.1:30975/js/electerm-1.38.81.js:61:5380)
    at Worker._p (http://127.0.0.1:30975/js/electerm-1.38.81.js:61:6272)

### What should have happened?(期望的结果)

正常删除成功

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

例如FinalShell，使用同样账号进去（权限一致），能正常删除文件夹

### Additional information(其他任何相关信息)

Error: sftp.list is not a function
    at http://127.0.0.1:30975/js/electerm-1.38.81.js:86:16028
    at Object.resolve (http://127.0.0.1:30975/js/electerm-1.38.81.js:61:5380)
    at Worker._p (http://127.0.0.1:30975/js/electerm-1.38.81.js:61:6272)

**Comment by langren1353** [comment]
应该来说还是比较好复现的，我这边换了一台电脑试试看
奇怪，无法复现了，只能考虑是换电脑后好了
