### ISSUE TITLE
intel oneapi环境变量加入.bashrc后Sftp无法打开

### ISSUE THREAD

**Issue by Shihang-Hu** [electerm/electerm#3413]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-1.39.2-win-x64-installer.exe

### Platform detail (平台详情)

linux

### What steps will reproduce the bug?(重新问题的详细步骤)

我将命令`source /opt/intel/oneapi/setvars.sh intel64`加入到'.bashrc'文件后, 即开机自动设置intel oneapi环境变量, Sftp功能无法打开, 报错如下  
```
Error: Packet length 537541178 exceeds max length of 262144
    at <http://127.0.0.1:30975/js/electerm-1.39.2.js:86:16028>
    at Object.resolve (<http://127.0.0.1:30975/js/electerm-1.39.2.js:61:5428>)
    at Worker.Dp (<http://127.0.0.1:30975/js/electerm-1.39.2.js:61:6320>)
```
报错图片如下:  
![2024-05-10 06-10-14-135](https://github.com/electerm/electerm/assets/102537099/319f3708-9fad-42cf-b29b-1dc6a4190810)

### What should have happened?(期望的结果)

修改好BUG即可, 谢谢. 

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

未尝试使用过其他同类软件, vscode SSH没有问题.

**Comment by zxdong262** [comment]
请问 ssh登录后ls -al会有很多文件吗

**Comment by zxdong262** [comment]
根据https://www.zhihu.com/question/421105440 可能是 `source /opt/intel/oneapi/setvars.sh intel64` 导致大量输出 ，也许可以试试 `source /opt/intel/oneapi/setvars.sh intel64 1>/dev/null 2>&1`?

**Comment by zxdong262** [comment]
软件端还是没有解决，其他软件应该是能够正确处理这种情况

**Comment by zxdong262** [comment]
https://github.com/mscdex/ssh2/issues/1048

**Comment by zxdong262** [comment]
将在下个版本修复这个问题，即便引入过多文字，也能正确显示sftp

**Comment by zxdong262** [comment]
最新版已经解决
