### ISSUE TITLE
Error: Permission denied     at http://127.0.0.1:30975/js/electerm-1.39.18.js:86:16028     at Object.resolve (http://127.0.0.1:30975/js/electerm-1.39.18.js:61:5428)     at Worker.Lp (http://127.0.0.1:30975/js/electerm-1.39.18.js:61:6320)

### ISSUE THREAD

**Issue by A5v8m6damHaleyo2w** [electerm/electerm#3435]
### Electerm Version and download file extension(Electerm版本和下载文件后缀)

electerm-xx.xx.xx-win-x64-installer.exe

### Platform detail (平台详情)

windows10

### What steps will reproduce the bug?(重新问题的详细步骤)

Error: Permission denied
    at http://127.0.0.1:30975/js/electerm-1.39.18.js:86:16028
    at Object.resolve (http://127.0.0.1:30975/js/electerm-1.39.18.js:61:5428)
    at Worker.Lp (http://127.0.0.1:30975/js/electerm-1.39.18.js:61:6320)

切換root用戶的目录使用sftp文件传输就会复现

### What should have happened?(期望的结果)

能够正常对目录进行文件sftp传输

### Would this happen in other terminal app(是否能够在其他同类软件重现这个问题)

没试过

**Comment by zxdong262** [comment]
是不是要传输的文件没有权限？

**Comment by A5v8m6damHaleyo2w** [comment]
> 是不是要传输的文件没有权限？

是root用户下的目录,都有权限,重新授权也没有效果

**Comment by zxdong262** [comment]
> > 是不是要传输的文件没有权限？
> 
> 不是,切换普通用户就可以正常传输,对同一个文件
创建的书签不是root用户？如果是登陆后切换是不行的，可以另外创建一个root用户的书签

**Comment by zxdong262** [comment]
sftp的用户是创建时候就决定的，ssh用户改变不会影响到sftp的身份
