### ISSUE TITLE
sftp error  Error: No such file

### ISSUE THREAD

**Issue by blue-bird1** [electerm/electerm#791]
## electerm version:
0.24.33
## operating system(linux, macos, or windows?):
window
## Expected Behavior

sftp 
## Current Behavior

error tip
## Steps to Reproduce

1.ssh server
2.error tip

## Detailed Description

```
sftp error
electerm.0.24.33-6dcabb68335774c5960f39a0e83e5acbc1b69aa9.js:5 No such file
electerm.0.24.33-6dcabb68335774c5960f39a0e83e5acbc1b69aa9.js:5 Error: No such file
    at SFTPStream._transform (C:\Users\Administrator\Downloads\electerm-0.24.33-win (1).tar\electerm-0.24.33-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\sftp.js:412:27)
    at SFTPStream.Transform._read (_stream_transform.js:186:10)
    at SFTPStream._read (C:\Users\Administrator\Downloads\electerm-0.24.33-win (1).tar\electerm-0.24.33-win-x64\resources\app.asar\node_modules\ssh2-streams\lib\sftp.js:183:15)
    at SFTPStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at SFTPStream.Writable.write (_stream_writable.js:290:11)
    at Channel.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Channel.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Channel.Readable.push (_stream_readable.js:208:10)
    at SSH2Stream.<anonymous> (C:\Users\Administrator\Downloads\electerm-0.24.33-win (1).tar\electerm-0.24.33-win-x64\resources\app.asar\node_modules\ssh2\lib\Channel.js:166:15)
    at emitOne (events.js:116:13)
    at SSH2Stream.emit (events.js:211:7)
```

**Comment by zxdong262** [comment]
https://github.com/electerm/electerm/commit/f3c5db024ec9cc63839522c27c539ab5ec7cd9bd

**Comment by blue-bird1** [comment]
I try new version,but it not work

**Comment by blue-bird1** [comment]
my /root/ dir have link dir
```
lrwxrwxrwx   1 root root   13 Sep 11 01:22 .multirust -> /root/.rustup/
```
I rm it ,sftp will work very well

**Comment by zxdong262** [comment]
@blue-bird1 Thank you for the feedback.

**Comment by zxdong262** [comment]
@blue-bird1 Released new version with bug fix, should be ok now
